import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

type Props = {
   title: string;
   description?: string;
};

export const HeadMeta = (props: Props) => {
   const { title, description } = props;

   return (
      <Head>
         <title>{title}</title>
         <meta name="description" content={description ?? 'Generated by create next app'} />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
      </Head>
   );
};
