import { BaseLayout } from '@/components/baseLayout/BaseLayout';
import { Metadata, NextPage } from 'next';
import { PropsWithChildren } from 'react';
export const metadata: Metadata = {
   title: 'Characters',
   description: 'Generated by create next app',
};

const Layout: NextPage<PropsWithChildren> = ({ children }) => {
   return <BaseLayout>{children}</BaseLayout>;
};

export default Layout;
